<script>
function simpleTryCatch() {
    let resoult; 

    try {
        resoult = x / 21; 
    } catch (error) {
        console.log(error.message);
    }
    finally{
        console.log('allways run error or not');
    }
}

// simpleTryCatch();



function customTryCatch() {
    let resoult; 

    try {
        resoult = x / 21; 
    } catch (error) {
       throw{
            'message' : ' customTryCatch() the following error: ' + error.message + '  - ' + error.type,
            'name' : 'CustomError'
         };
    }
    finally{
        console.log('allways run error or not');

    }
}

//customTryCatch();

</script>